## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный единицами

In [3]:
o = np.ones(10)
print(o)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать вектор размера 10, заполненный числом 2.5

In [4]:
c = np.ones(10)*2.5
print(c)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [5]:
z = np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Развернуть вектор (первый становится последним)

In [6]:
a = np.arange(10)
print(a)
a = a[::-1]
print(a)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [7]:
M = np.arange(9).reshape(3,3)
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [8]:
a = [1,2,0,0,4,0]
print(np.nonzero(a))

(array([0, 1, 4], dtype=int64),)


Создать 3x3 единичную матрицу

In [9]:
M = np.eye(3)
print(M)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Создать массив 3x3x3 со случайными значениями

In [10]:
M = np.random.random((3,3,3))
print(M)

[[[0.35650537 0.47132434 0.23293515]
  [0.54830127 0.206958   0.14294707]
  [0.57667514 0.6840123  0.3717076 ]]

 [[0.75538209 0.14261052 0.38808921]
  [0.67151815 0.09975408 0.73060715]
  [0.16504699 0.35168442 0.86069086]]

 [[0.85612987 0.86954624 0.9934381 ]
  [0.57431358 0.59108094 0.79707494]
  [0.01134248 0.65293404 0.06576708]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [11]:
a = np.random.random(30)
print(a)
print(np.mean(a))

[0.17202249 0.17695409 0.71568497 0.30099596 0.84927745 0.41761669
 0.26924394 0.93303709 0.98989375 0.48133385 0.19535004 0.7298583
 0.05887976 0.02410578 0.90118724 0.43374996 0.53642694 0.79724234
 0.25761393 0.24164145 0.99840148 0.67231098 0.01365048 0.78746518
 0.31468589 0.85541357 0.84546657 0.02790477 0.03318748 0.9284032 ]
0.4986335204248423


Перемножить матрицы 5x3 и 3x2

In [12]:
A = np.ones((5,3))
B = np.ones((3,2))
print(f'A = ', A, ' \n B = ', B, sep='\n', end='\n\n') #f-string doesn't work with numpy-matrix
M = np.dot(A, B)
print(f'A x B = \n', M)

A = 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
 
 B = 
[[1. 1.]
 [1. 1.]
 [1. 1.]]

A x B = 
 [[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [13]:
a = np.random.random(10)
eps = np.finfo(np.float32).eps
a = (1 - 2 * eps) * a + eps # excluding possible 0
print(eps, '<= a[:] <=', (1 - 2 * eps) * (1 - eps) + eps)
print('a = ', a)

1.1920929e-07 <= a[:] <= 0.9999997615814493
a =  [0.0429543  0.39486012 0.38502745 0.22841317 0.55028957 0.17942123
 0.83235916 0.21975492 0.99506352 0.34114811]


Заменить максимальный элемент на ноль

In [14]:
a = np.random.random(10)
print('max =', a.max(), ' position =', a.argmax())
a[a.argmax()] = 0
print(a)

max = 0.9192047217147571  position = 4
[0.69149295 0.11866286 0.76836661 0.37886113 0.         0.72408491
 0.87923555 0.62677006 0.667926   0.20913687]


Преобразовать массив из float в int

In [15]:
a = np.arange(10, dtype=np.float)
print(a)
print(a.dtype)
a = np.array(a, dtype=np.int)
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64
[0 1 2 3 4 5 6 7 8 9]
int32


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [16]:
import scipy.spatial

A = np.random.random((10,2))
dist = scipy.spatial.distance.cdist(A,A)
print(dist)

[[0.         0.25329396 0.99501828 1.08903131 0.55521574 0.49427348
  0.72870778 0.09517375 0.22807167 0.48580208]
 [0.25329396 0.         0.83570225 0.88612797 0.59288833 0.3466592
  0.61524955 0.2835297  0.25684016 0.39545543]
 [0.99501828 0.83570225 0.         0.24582135 0.67816662 0.50296777
  0.2977415  0.94146216 0.78314226 0.52116807]
 [1.08903131 0.88612797 0.24582135 0.         0.87709417 0.60500366
  0.49012361 1.05389033 0.90290403 0.66237843]
 [0.55521574 0.59288833 0.67816662 0.87709417 0.         0.40137022
  0.38808521 0.4628959  0.35303875 0.2902379 ]
 [0.49427348 0.3466592  0.50296777 0.60500366 0.40137022 0.
  0.27007351 0.45006929 0.29798487 0.11139263]
 [0.72870778 0.61524955 0.2977415  0.49012361 0.38808521 0.27007351
  0.         0.66417132 0.50583257 0.24291343]
 [0.09517375 0.2835297  0.94146216 1.05389033 0.4628959  0.45006929
  0.66417132 0.         0.15879869 0.42294804]
 [0.22807167 0.25684016 0.78314226 0.90290403 0.35303875 0.29798487
  0.50583257 0.158798

Случайно расположить p элементов в 2D массив

In [17]:
n = 3
p = 2
A = np.zeros((n,n))
print(A)
c = np.random.choice(range(n*n), p, replace=False)
print('choice =', c)
np.put(A, c, 1)
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
choice = [5 2]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [18]:
a = np.array([1, 2, 3, 4, 5])
number_z = 3
b = np.zeros(a.size + number_z*(a.size-1))
b[::number_z+1] = a
print(b)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [19]:
a = np.random.randint(0,10,100)
print(a)
print(np.bincount(a).argmax())

[4 6 4 6 8 0 0 2 4 4 0 6 0 8 5 7 3 2 4 5 4 3 7 9 3 4 2 9 9 3 3 7 7 3 5 4 2
 4 7 2 1 8 9 5 0 7 3 8 2 4 7 5 8 6 3 0 1 0 8 5 8 8 0 7 0 3 8 9 7 7 1 3 7 3
 6 8 9 0 0 5 7 4 1 8 3 5 6 6 8 3 7 7 1 6 4 1 3 9 0 2]
3


Найти n наибольших значений в массиве

In [20]:
a = np.random.randint(0,10,100)
n = 5
print(a)
print(a[np.argpartition(-a,np.arange(n))[:n]])

[6 7 3 5 4 3 2 2 2 1 2 7 8 9 5 2 6 4 0 6 7 2 3 0 7 1 5 5 7 4 7 3 7 7 2 7 2
 2 9 7 0 9 5 5 6 9 6 0 2 9 1 9 8 9 6 1 9 4 7 8 6 6 9 0 2 0 8 2 2 4 4 3 1 9
 3 8 4 8 7 5 0 7 5 6 7 8 4 1 5 8 7 4 4 3 9 5 0 5 0 7]
[9 9 9 9 9]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [21]:
import pandas as pd

In [22]:
food_df = pd.read_csv('en.openfoodfacts.org.products.tsv',sep='\t',low_memory=False)

Посмотреть первые 5 записей

In [23]:
food_df.head()

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [24]:
len(food_df.index)

356027

Сколько столбцов в наборе данных?

In [25]:
len(food_df.columns)

163

Напечатайте все названия столбцов

In [26]:
print(list(food_df))

['code', 'url', 'creator', 'created_t', 'created_datetime', 'last_modified_t', 'last_modified_datetime', 'product_name', 'generic_name', 'quantity', 'packaging', 'packaging_tags', 'brands', 'brands_tags', 'categories', 'categories_tags', 'categories_en', 'origins', 'origins_tags', 'manufacturing_places', 'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en', 'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities', 'cities_tags', 'purchase_places', 'stores', 'countries', 'countries_tags', 'countries_en', 'ingredients_text', 'allergens', 'allergens_en', 'traces', 'traces_tags', 'traces_en', 'serving_size', 'no_nutriments', 'additives_n', 'additives', 'additives_tags', 'additives_en', 'ingredients_from_palm_oil_n', 'ingredients_from_palm_oil', 'ingredients_from_palm_oil_tags', 'ingredients_that_may_be_from_palm_oil_n', 'ingredients_that_may_be_from_palm_oil', 'ingredients_that_may_be_from_palm_oil_tags', 'nutrition_grade_uk', 'nutrition_grade_fr', 'pnns_groups_1', 

Какое название у 105 столбца?

In [27]:
print(list(food_df)[104])

-glucose_100g


Какой тип наблюдений в 105 столбце?

In [28]:
food_df.dtypes[104]

dtype('float64')

Как проиндексирован набор данных?

In [29]:
food_df.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [30]:
food_df.loc[18,'product_name']

'Lotus Organic Brown Jasmine Rice'

In [31]:
# clear memmory
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [32]:
import pandas as pd

In [33]:
chipo_df = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep='\t')

Как много продуктов стоят более чем $10.00?

In [34]:
chipo_df['item_price'] = chipo_df['item_price'].str.replace('$', '', regex=False).astype('float64')
chipo_df.insert(len(chipo_df.columns), 'price', chipo_df.item_price / chipo_df.quantity)

In [35]:
#len(chipo_df[chipo_df.price > 10.0].index)
len(chipo_df[chipo_df.price > 10.0].item_name.unique())

25

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [36]:
chipo_df.groupby(['item_name','price'])['price'].size()

item_name              price
6 Pack Soft Drink      6.49      54
Barbacoa Bowl          8.69       3
                       8.99       8
                       9.25      28
                       11.48      6
                       11.49      1
                       11.75     20
Barbacoa Burrito       8.69       2
                       8.99      19
                       9.25      46
                       11.08      1
                       11.48      1
                       11.75     22
Barbacoa Crispy Tacos  8.99       2
                       9.25       5
                       11.48      1
                       11.75      3
Barbacoa Salad Bowl    9.39       5
                       11.89      5
Barbacoa Soft Tacos    8.99       2
                       9.25      15
                       11.48      1
                       11.75      7
Bottled Water          1.09      27
                       1.50     135
Bowl                   7.40       1
                       7.40       1

Отсортировать по имени предмета

In [37]:
chipo_df.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description  item_price  price  
3389                                        [Diet Coke]       12.98   6.49  
341                                         [Diet Coke]        6.49   6.49  
1849                                             [Coke]        6.49   6.49  
1860                                        [Diet Coke]        6.49   6.49  
2713                                             [Coke]        6.49   6.49  
3422                                             [Coke]        6.49   6.49  
553                                         [Diet Coke]        6.49   6.49  
1916                                        [Diet Coke]        6.49   6.49  
1922                                             [Coke]        6.49   6.49  
1937                                        [Diet Coke]        6.49   6.49  
3836                                             [Coke]        6.49   6.49  
298                                            [Sprite]        6.49   6.49  
1976                                        [Diet Coke]        6.49   6.49  
1167         

Сколько было заказано самого дорогого предмета?

In [38]:
#chipo_df[chipo_df.price==chipo_df.price.max()].groupby(['item_name'])['quantity'].sum() # если нужно узнать, что за предметы
chipo_df.quantity[chipo_df.price==chipo_df.price.max()].sum()

30

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [39]:
chipo_df[chipo_df.item_name == 'Veggie Salad Bowl'].groupby(['item_name'])['quantity'].sum()

item_name
Veggie Salad Bowl    18
Name: quantity, dtype: int64

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [40]:
chipo_df['item_name'][(chipo_df.item_name == 'Canned Soda') & (chipo_df.quantity > 1)].count()

20